### ISSUE TITLE
scripts do not work on Arch Linux with python3.7

### ISSUE THREAD

**Issue by tixetsal** [clinton-hall/nzbToMedia#1646]
**Describe the bug**

nzbtomedia scripts do not work on Arch Linux with python3.7 . The scripts fail with error messages, the last of which mentions "AttributeError: 'NoneType' object has no attribute 'isfile'"

I had read that switching to the nightly build might resolve the issue, but this did not appear to help me. I was able to get the scripts to work again by manually editing environmental variable to point at python2.7 but I suspect the next auto-update will cause the issue to reappear.

**Technical Specs**
1. Arch Linux
2. Python3.7
3. sabnzbd
4. Radarr and Sonarr

**Expected behavior**
The scripts should execute and sort media as is appropriate, but they error out

**Log**
Traceback (most recent call last):
File "/opt/sabnzbd/scripts/nzbToMedia/nzbToNzbDrone.py", line 259, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/opt/sabnzbd/scripts/nzbToMedia/nzbToMedia.py", line 942, in main
download_id='', failure_link=''.join(args[8:]))
File "/opt/sabnzbd/scripts/nzbToMedia/nzbToMedia.py", line 796, in process
if extract == 1 and not (status > 0 and core.NOEXTRACTFAILED):
TypeError: '>' not supported between instances of 'str' and 'int'
Exception ignored in: <function PosixProcess.__del__ at 0x7f0644374320>
Traceback (most recent call last):
File "/opt/sabnzbd/scripts/nzbToMedia/core/utils/processes.py", line 95, in __del__
AttributeError: 'NoneType' object has no attribute 'isfile'

**Comment by clinton-hall** [comment]
Can you please test the `SAB-1` branch?
I believe the issue here is that the SAB status is being sent as a string, not an integer...
Now, in Py2, this is (incorrectly) handled such that status is ALWAYS greater than 0 (i.e. a bug) but in Py3 this crashes as per your log.

The good news is later on this status is forced to integer anyway, so it was just this 1 check where it was not handled correctly... but the change I have made in `SAB-1` branch should ensure this is always handled correctly.

**Comment by tixetsal** [comment]
Well done, sir! The scripts are now running as expected. I really appreciate the quick response, and I also appreciate you taking the time to explain the solution. 

Thanks for your time and hard work. Take care.

**Comment by clinton-hall** [comment]
Thanks for confirming.
I have merged into nightly. SAB-1 branch is now gone, but you can move to nightly and keep up to date.

**Comment by Mickroz** [comment]
Im running against the same problem, but when running the script it says its up to date running on version e165bbcefc9686c333978f79e72c0e3e8cba9c56, which is clearly older?
Im on master branch

**Comment by Mickroz** [comment]
Fixed it after downloading a new nzb, it auto updated after that.

**Comment by tixetsal** [comment]
Hi. This issue appears to have resurfaced for me today. 

Have I done something to reintroduce this issue, and/or do you need any data?

`Traceback` (most recent call last):
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/urllib3/connectionpool.py", line 384, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/urllib3/connectionpool.py", line 380, in _make_request
httplib_response = conn.getresponse()
File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
response.begin()
File "/usr/lib/python3.7/http/client.py", line 306, in begin
version, status, reason = self._read_status()
File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/lib/python3.7/socket.py", line 589, in readinto
return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/requests/adapters.py", line 449, in send
timeout=timeout
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/urllib3/connectionpool.py", line 638, in urlopen
_stacktrace=sys.exc_info()[2])
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/urllib3/util/retry.py", line 367, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/urllib3/packages/six.py", line 686, in reraise
raise value
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/urllib3/connectionpool.py", line 386, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/urllib3/connectionpool.py", line 306, in _raise_timeout
raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=8081): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/sabnzbd/scripts/nzbToMedia/nzbToNzbDrone.py", line 259, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/opt/sabnzbd/scripts/nzbToMedia/nzbToMedia.py", line 942, in main
download_id='', failure_link=''.join(args[8:]))
File "/opt/sabnzbd/scripts/nzbToMedia/nzbToMedia.py", line 805, in process
result = tv.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "/opt/sabnzbd/scripts/nzbToMedia/core/auto_process/tv.py", line 370, in process
command_status = command_complete(url, params, headers, section)
File "/opt/sabnzbd/scripts/nzbToMedia/core/auto_process/common.py", line 39, in command_complete
r = requests.get(url, params=params, headers=headers, stream=True, verify=False, timeout=(30, 60))
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/requests/api.py", line 75, in get
return request('get', url, params=params, **kwargs)
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/requests/api.py", line 60, in request
return session.request(method=method, url=url, **kwargs)
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/opt/sabnzbd/scripts/nzbToMedia/libs/common/requests/adapters.py", line 529, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8081): Read timed out. (read timeout=60)
Exception ignored in: <function PosixProcess.__del__ at 0x7fc09ed96290>
Traceback (most recent call last):
File "/opt/sabnzbd/scripts/nzbToMedia/core/utils/processes.py", line 95, in __del__
AttributeError: 'NoneType' object has no attribute 'isfile'``

**Comment by clinton-hall** [comment]
very different error now.... these all look to be timeout issues for localhost:8081 not responding

can you confirm Sonarr is online and responding?

**Comment by tixetsal** [comment]
Yes, Sonarr is up now. The error started after I cloned my OS drive from an older NVME to a new 970 Pro drive, so I'm willing to admit that it may be something I did that caused this issue.

What struck me as strange was that the "object has no attribute 'isfile'``" message reappeared. To work around this, I edited the scripts to point back at Python2.7, so that my queue would process, as I did before, and the remainder of the Q was processed once I resolved the issue with Radar. 

Would you like for me to try anything specific and post the output? Thanks.

**Comment by Mickroz** [comment]
im getting the same on a arch install with couchpotato
```
Traceback (most recent call last):
File "/scripts/nzbToMedia/nzbToCouchPotato.py", line 272, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/scripts/nzbToMedia/nzbToMedia.py", line 942, in main
download_id='', failure_link=''.join(args[8:]))
File "/scripts/nzbToMedia/nzbToMedia.py", line 803, in process
result = movies.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "/scripts/nzbToMedia/core/auto_process/movies.py", line 356, in process
release = get_release(base_url, imdbid, download_id, release_id)
File "/scripts/nzbToMedia/core/auto_process/movies.py", line 514, in get_release
for x2 in results.values():
RuntimeError: dictionary changed size during iteration
Exception ignored in: <function PosixProcess.__del__ at 0x7f353dde80e0>
Traceback (most recent call last):
File "/scripts/nzbToMedia/core/utils/processes.py", line 95, in __del__
AttributeError: 'NoneType' object has no attribute 'isfile'
```

Sickchill fails aswell, but in the debug log it echo's the login page html.

**Comment by clinton-hall** [comment]
@Mickroz 
So is this working for you now?

**Comment by clinton-hall** [comment]
@tixetsal 
Whenever the script crashes it will produce the final error
```
Exception ignored in: <function PosixProcess.del at 0x7fc09ed96290>
Traceback (most recent call last):
File "/opt/sabnzbd/scripts/nzbToMedia/core/utils/processes.py", line 95, in del
AttributeError: 'NoneType' object has no attribute 'isfile'``
```
This is part of the "already running" check.
But everything before this tells us what went wrong, and this was different this time.

Should be ok to switch back to python3 and confirm if in-fact there is an issue.

**Comment by Mickroz** [comment]
@clinton-hall it fixed it for SickChill yes, and im not getting the error again with couchpotato with a new download, so , i cannot tell you where that came from, will try the same download again and see what happens.

**Comment by tixetsal** [comment]
@clinton-hall I switched back to python3 and all is well. Thank you!
