### ISSUE TITLE
PostProcessing fails with error about STARTF_USESHOWWINDOW

### ISSUE THREAD

**Issue by mrginogit** [clinton-hall/nzbToMedia#787]
Having some trouble getting this to work with SabNZBD 0.7.20.  Getting the below error for movies and TV shows:
...
Traceback (most recent call last):
  File "C:\Program Files (x86)\SABnzbd\_AddOns_\Post-ProcessingScripts\nzbToCouchPotato.py", line 246, in <module>
    import nzbToMedia
  File "C:\Program Files (x86)\SABnzbd\_AddOns_\Post-ProcessingScripts\nzbToMedia.py", line 503, in <module>
    import core
  File "C:\Program Files (x86)\SABnzbd\_AddOns_\Post-ProcessingScripts\core\__init__.py", line 28, in <module>
    from core.autoProcess.autoProcessComics import autoProcessComics
  File "C:\Program Files (x86)\SABnzbd\_AddOns_\Post-ProcessingScripts\core\autoProcess\autoProcessComics.py", line 6, in <module>
    from core.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
  File "C:\Program Files (x86)\SABnzbd\_AddOns_\Post-ProcessingScripts\core\nzbToMediaUtil.py", line 19, in <module>
    from core.linktastic import linktastic
  File "C:\Program Files (x86)\SABnzbd\_AddOns_\Post-ProcessingScripts\core\linktastic\linktastic.py", line 30, in <module>
    info.dwFlags |= subprocess.STARTF_USESHOWWINDOW
AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'
...

Also not quite sure why it even mentions the Comics script, Sab is calling the CP script.  

Found this thread at https://sickrage.tv/forums/forum/help-support/nzbtomedia-support/18217-post-processing-started-failing where you ask what version of python and pywin, but the OP never responded.  

What versions are supported/required?  I am currently using python 2.7.150 with pywin 2.7.  What should I be using for the STARTF_USESHOWWINDOW feature to work?

**Comment by clinton-hall** [comment]
so when you installed Pywin2.7, this needed to be the matching version for Python (2.7.150)

What windows version are you using? If you open a python windows and do 
```import subprocess
subprocess.STARTF_USESHOWWINDOW
```
what does it output?

**Comment by mrginogit** [comment]
Hey clinton.hall,

Thanks for the quick response!  I've been using these versions of pywin and python for about 3 years now with CP/SB/etc, just went back and checked the exact build of pywin.  According to C:\Python27\Lib\site-packages\pywin32.version.txt, it's 217.

Also just ran the command you mentioned, output below:

Python 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ```import subprocess
  File "<stdin>", line 1
    ```import subprocess
            ^
SyntaxError: invalid syntax
>>> import subprocess
>>> subprocess.STARTF_USESHOWWINDOW
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'

**Comment by clinton-hall** [comment]
not sure what to do here... if you can't even import .

I notice my earlier post didn't display correctly. I have just fixed this. Please try the command again... no spaces before `import subprocess`

**Comment by mrginogit** [comment]
same thing unfortunately

```
Python 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.STARTF_USESHOWWINDOW
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'
>>>
```

what build of pywin should i be using with python 2.7.150?  or maybe a better question is, what versions of both python and pywin are you using in your environment?

**Comment by mrginogit** [comment]
Hi clinton-hall, can you share what versions of pywin and python you are running?

**Comment by clinton-hall** [comment]
None... I hate Windows... :P
The system I did my previous tests on is no more, so I can't confirm what versions were tested. I intend to set up a system to test, but just been too busy.

**Comment by clinton-hall** [comment]
ok...
`python-2.7.10.msi` https://www.python.org/ftp/python/2.7.10/python-2.7.10.msi
`pywin32-218.win32-py2.7.exe` http://sourceforge.net/projects/pywin32/files/pywin32/Build%20218/pywin32-218.win32-py2.7.exe/download

```
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import subprocess
>>> subprocess.STARTF_USESHOWWINDOW
1
>>> 
```

**Comment by mrginogit** [comment]
Closing the loop on this, can't believe how fast time went by.  Upgrading to the builds clinton-hall posted above resolved my issue.  Thank you!!
