### ISSUE TITLE
Directory issue?

### ISSUE THREAD

**Issue by Ordovicium** [clinton-hall/nzbToMedia#1498]
Since I upgrade from 11.03 to the latest version, my sickbeard doesn't work anymore. I get following error in SabNZB:

```Changing to directory: /volume1/@appstore/sabnzbd/var/scripts

-- Cleaning bytecode --
Error: [Errno 2] No such file or directory
Directory is not a git repository
Returning to directory:  /volume1/@appstore/sabnzbd/share/SABnzbd

-- Cleanup finished --

Traceback (most recent call last):
File "/usr/local/sabnzbd/var/scripts/nzbToSickBeard.py", line 264, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia.py", line 780, in main
core.initialize(section)
File "/volume1/@appstore/sabnzbd/var/scripts/core/__init__.py", line 300, in initialize
if not config.migrate():
File "/volume1/@appstore/sabnzbd/var/scripts/core/configuration.py", line 247, in migrate
CFG_NEW.write()
File "/volume1/@appstore/sabnzbd/var/scripts/libs/common/configobj.py", line 2128, in write
with open(self.filename, 'wb') as h:
IOError: [Errno 13] Permission denied: '/volume1/@appstore/sabnzbd/var/scripts/autoProcessMedia.cfg'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.PosixProcess object at 0xb7344f4c>> ignored`
```
But I more or less copied the cfg file. Thank you for support.

**Comment by labrys** [comment]
Can you check permissions and possibly try reverting to 11.03 and see if the problem still exists.

**Comment by Ordovicium** [comment]
I don't have the files anymore. I chmod now everything in the script folder with 777. No result. The only reason for upgrade was radarr, which wasn't supported in the old version.

`[21:03:03] [INFO]::MAIN: Loading config from [/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/autoProcessMedia.cfg]
[21:03:03] [INFO]::MAIN: Checking database structure...
[21:03:03] [INFO]::MAIN: Database upgrade required: Initial Schema
[21:03:03] [INFO]::MAIN: Checking if git needs an update
[21:03:05] [INFO]::MAIN: No update needed
[21:03:05] [INFO]::MAIN: nzbToMedia Version:e386eaaec2e421e0fcdab5002756c28139deb454 Branch:master (Linux 3.2.40)
[21:03:05] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
[21:03:05] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[21:03:05] [INFO]::MAIN: #########################################################
[21:03:05] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[21:03:05] [INFO]::MAIN: #########################################################
[21:03:05] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[21:03:05] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[21:03:05] [INFO]::MAIN: Calling SickBeard:tv to post-process:Yxxxx.nzb
[21:03:06] [INFO]::MAIN: Attempting to auto-detect tv fork
Changing to directory: /volume1/@appstore/sabnzbd/var/scripts/nzbToMedia

-- Cleaning bytecode --
Removing cleanup.pyc
Removing nzbToMedia.pyc

Removing cleanup.pyc
Removing nzbToMedia.pyc


-- Cleaning folders: ('core', 'libs') --
No folders to clean

Returning to directory:  /volume1/@appstore/sabnzbd/share/SABnzbd

-- Cleanup finished --

Traceback (most recent call last):
File "/usr/local/sabnzbd/var/scripts/nzbToMedia/nzbToSickBeard.py", line 264, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/nzbToMedia.py", line 885, in main
download_id='', failure_link=''.join(args[8:]))
File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/nzbToMedia.py", line 750, in process
result = tv.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/core/auto_process/tv.py", line 36, in process
fork, fork_params = auto_fork(section, input_category)
File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/core/forks.py", line 86, in auto_fork
optional_parameters = r.json()['data']['data']['optionalParameters'].keys()
KeyError: 'data'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.PosixProcess object at 0xb73618ac>> ignored`

**Comment by Trotter73** [comment]
Hi,

I'm seeing the same on Windows 10.. Its preventing the script from upgrading, as I'm currently seeing #1503 as well...

`Changing to directory: C:\Utils\nzbToMedia

-- Cleaning bytecode --
Error: [Error 2] The system cannot find the file specified
Directory is not a git repository
Returning to directory:  C:\Users\Martin

-- Cleanup finished --`

**Comment by labrys** [comment]
@Ordovicium After the permissions change you are getting a different error which means the original error was likely a permissions problem.  As for your follow up error I'll take a look and see if I can find a cause for it.

**Comment by labrys** [comment]
@Trotter73 since you are seeing the same issue as #1503, we'll continue your troubleshooting there.

**Comment by labrys** [comment]
@Ordovicium I will be adding some additional logging for your issue in the nightly branch... Once I do, could you please check it out and post the debug logs?

**Comment by labrys** [comment]
@Ordovicium Latest nightly has added logging and some cleanup in the fork detection code.

**Comment by JoopNL** [comment]
I've got the same issue, well almost in any case. This is with a clean install from master, after that I switched to nightly, but issue remains the same and I don't see additional logging. The clean install was because I was also seeing #1503, and couldn't get that fixed. #1503 is fixed now with the clean install, but directory errors remain.

This had been running without issues on my Synology NAS with autoupdate enabled for years, but it broke around christmas.
 
Full console output of manual run with debug log. Some help would be appreciated.

```
root@NAS:/usr/local/sabnzbd/var/scripts# ./nzbToMedia.py

-- Cleaning bytecode --
Error: [Errno 2] No such file or directory

-- Cleaning folders: ['libs', 'core'] --
Error: [Errno 2] No such file or directory

-- Cleanup finished --

[19:20:59] [INFO]::MAIN: Loading config from [/volume1/@appstore/sabnzbd/var/scripts/autoProcessMedia.cfg]
[19:20:59] [INFO]::MAIN: Checking database structure...
[19:20:59] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[19:20:59] [DEBUG]::MAIN: InitialSchema upgrade not required
[19:20:59] [DEBUG]::MAIN: Checking if we can use git commands: '/usr/local/git/bin/git' version
[19:20:59] [DEBUG]::MAIN: Executing '/usr/local/git/bin/git' version with your shell in /volume1/@appstore/sabnzbd/var/scripts
[19:20:59] [DEBUG]::MAIN: '/usr/local/git/bin/git' version : returned successful
[19:20:59] [DEBUG]::MAIN: Using: '/usr/local/git/bin/git'
[19:20:59] [DEBUG]::MAIN: Executing '/usr/local/git/bin/git' symbolic-ref -q HEAD with your shell in /volume1/@appstore/sabnzbd/var/scripts
[19:20:59] [DEBUG]::MAIN: '/usr/local/git/bin/git' symbolic-ref -q HEAD : returned successful
[19:20:59] [INFO]::MAIN: Checking if git needs an update
[19:20:59] [DEBUG]::MAIN: Executing '/usr/local/git/bin/git' rev-parse HEAD with your shell in /volume1/@appstore/sabnzbd/var/scripts
[19:20:59] [DEBUG]::MAIN: '/usr/local/git/bin/git' rev-parse HEAD : returned successful
[19:20:59] [DEBUG]::MAIN: Executing '/usr/local/git/bin/git' fetch origin with your shell in /volume1/@appstore/sabnzbd/var/scripts
[19:21:00] [DEBUG]::MAIN: '/usr/local/git/bin/git' fetch origin : returned successful
[19:21:00] [DEBUG]::MAIN: Executing '/usr/local/git/bin/git' rev-parse --verify --quiet '@{upstream}' with your shell in /volume1/@appstore/sabnzbd/var/scripts
[19:21:00] [DEBUG]::MAIN: '/usr/local/git/bin/git' rev-parse --verify --quiet '@{upstream}' : returned successful
[19:21:00] [DEBUG]::MAIN: Executing '/usr/local/git/bin/git' rev-list --left-right '@{upstream}'...HEAD with your shell in /volume1/@appstore/sabnzbd/var/scripts
[19:21:00] [DEBUG]::MAIN: '/usr/local/git/bin/git' rev-list --left-right '@{upstream}'...HEAD : returned successful
[19:21:00] [DEBUG]::MAIN: cur_commit = df280c4bc34428f068b01da2b770af03f38f0f7d % (newest_commit)= df280c4bc34428f068b01da2b770af03f38f0f7d, num_commits_behind = 0, num_commits_ahead = 0
[19:21:00] [INFO]::MAIN: No update needed
[19:21:00] [INFO]::MAIN: nzbToMedia Version:df280c4bc34428f068b01da2b770af03f38f0f7d Branch:nightly (Linux 3.10.105)
[19:21:00] [WARNING]::MAIN: Failed to locate par2. Repair and rename using par files will not be possible!
[19:21:00] [INFO]::MAIN: #########################################################
[19:21:00] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[19:21:00] [INFO]::MAIN: #########################################################
[19:21:00] [DEBUG]::MAIN: Options passed into nzbToMedia: ['./nzbToMedia.py']
[19:21:00] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[19:21:00] [INFO]::MAIN: Searching /volume1/Media/Downloads/SABnzbd/Movies for mediafiles to post-process ...
[19:21:00] [DEBUG]::MAIN: No directories identified in CouchPotato:movies for post-processing
[19:21:00] [INFO]::MAIN: Searching  for mediafiles to post-process ...
[19:21:00] [ERROR]::MAIN: Failed to add directories from  for post-processing: [Errno 2] No such file or directory: ''
[19:21:00] [DEBUG]::MAIN: No directories identified in SickBeard:tv for post-processing
[19:21:00] [INFO]::MAIN: The ./nzbToMedia.py script completed successfully.
```

**Comment by labrys** [comment]
@JoopNL The cleanup script is intentionally left ignorant of the users `autoProcessMedia.cfg`.  The purpose is to make it as self-contained as possible to avoid being affected by code changes.  It isn't going to be able to clean 100% of user environments, but it should help the majority of the user base.  I may add a command line option to specify git path for a manual run.  Additionally I add clarification to the output that the error you received is really just a warning unless nzbToMedia fails to process files.
