### ISSUE TITLE
ImportError: cannot import name 'six' from 'pkg_resources.extern' (C:\Scripts\nzbToMedia\libs\common\pkg_resources\extern\__init__.py)

### ISSUE THREAD

**Issue by DrakeJones** [clinton-hall/nzbToMedia#1986]
Still maintaining the software, Clinton?

File "C:\Scripts\nzbToMedia\libs\common\pkg_resources\__init__.py", line 57, in <module>
    from pkg_resources.extern import six
ImportError: cannot import name 'six' from 'pkg_resources.extern' (C:\Scripts\nzbToMedia\libs\common\pkg_resources\extern\__init__.py)

Win10
Python 3.12
SABnbzd, qBittorrent
Radarr, Medusa

Expect Post to run
No log info

<<Edit>>  Falling back to Py 3.11 solves the problem.

**Comment by clinton-hall** [comment]
```Still maintaining the software, Clinton?```

Yes, in a very limited capacity.

I see a few posts here regarding python 3.12 so I'll try and set up some tests.

**Comment by clinton-hall** [comment]
and now it gets fun.
I have got this working with pthon3.12 but this is NOT compatible anymore with pyhton2.7!

So I may now have to finally archive Python2.7 version (and I believe Python 3.7 now has to be dropped as well)

**Comment by clinton-hall** [comment]
Hopefully now fixed in nightly branch.
Can you please switch to nightly and test?
